nelmio_api_doc:
    documentation:
        host: api.hicube.caida.org
        schemes: [https]
        info:
            title: Hi3 HTTP API
            description: Data and metadata API for the Hi3 platform.
            version: 1.0.0
        tags:
        - name: Time Series
          description: Time series data and metadata access calls
        - name: Expression
          description: Expression validation, annotation and metadata access calls.
        - name: Topographic
          description: Topographic data access calls
        - name: URL Shortener
          description: URL-shortening API

        responses:
            ResponseEnvelope:
                schema:
                    properties:
                        type:
                            type: "string"
                        requestParamters:
                            type: "object"
                        error:
                            type: "string"
                            description: "This field must be overridden."
                        data:
                            description: "This field must be overridden."

    areas: # to filter documented areas
        path_patterns:
            - ^/%env(API_VERSION)%(?!/docs|/_error)/
