security:
    providers:
        auth0_provider:
            id: App\Security\UserProvider
    firewalls:
        dev:
            pattern: ^/%env(API_VERSION)%/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            stateless: true
            simple_preauth:
                authenticator: jwt_auth.jwt_authenticator

    access_control:
        - { path: ^/%env(API_VERSION)%/docs, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: 'ROLE_api:query' }
