security:
    firewalls:
        dev:
            pattern: ^/%env(CH_API_VERSION)%/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            stateless: true
            guard:
                authenticators:
                  - App\Security\TokenAuthenticator

    access_control:
        - { path: ^/%env(CH_API_VERSION)%/docs, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: 'ROLE_api:query' }
